name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0

      - uses: actions/checkout@v3
      
      - name: Run tests
        run: make test
